"use client"
// pages/_app.tsx
import { Heading, withAuthenticator } from '@aws-amplify/ui-react';
import { Amplify } from 'aws-amplify';
import config from '@/amplifyconfiguration.json';
import '@aws-amplify/ui-react/styles.css';
import type { AppProps } from 'next/app';
import { Authenticator } from '@aws-amplify/ui-react';
import Logo from '@/components/logo/Logo';
// configure the Amplify client library with the configuration generated by `amplify sandbox`
Amplify.configure(config);

const components = {
  Header() {
    return (
      <div>
        <Logo />
      </div>
    );
  },
};

export default function Page() {
  return (
    <Authenticator components={components}>
      {({ signOut, user }) => (
        <main>
          <h1>Hello {user?.userId}</h1>
          <button onClick={signOut}>Sign out</button>
          <section>
            <h1> Daily Feed</h1>
          </section>
          <section>
            <h1>Your Current Milestone</h1>
          </section>
        </main>
      )}
    </Authenticator>
  )
}

// export default withAuthenticator(Page);